# Generated by Django 5.2.5 on 2025-12-03 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applybuesnessman_user_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supercategories', related_query_name='supercategories', to=settings.AUTH_USER_MODEL),
        ),
    ]
