# Generated by Django 5.2.5 on 2025-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applybuesnessman_business_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applybuesnessman',
            name='business_address',
            field=models.CharField(max_length=150),
        ),
    ]
