# Generated by Django 5.2.5 on 2025-10-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_applybuesnessman_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='applybuesnessman',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='applyrider',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved')], default='PENDING', max_length=50),
        ),
    ]
