# Generated by Django 5.2.5 on 2025-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_promocode_max_uses_per_user_promousage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
