# Generated by Django 5.2.5 on 2025-09-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_payment_method_order_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_account_number',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cashon',
            field=models.BooleanField(default=False),
        ),
    ]
