# Generated by Django 5.2.5 on 2025-09-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_order_payment_method_remove_order_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='GBP', max_length=10),
        ),
    ]
