# Generated by Django 5.2.5 on 2025-09-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderitems_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
